import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:resumate/models/website.dart';

class GitHubResult {
  final String repoUrl;
  final String? pagesUrl;
  final String commitSha;
  const GitHubResult({required this.repoUrl, this.pagesUrl, required this.commitSha});
}

class GitHubClient {
  final Dio _dio;
  final String _username;

  GitHubClient({required String token, required String username})
      : _username = username,
        _dio = Dio(BaseOptions(
          baseUrl: 'https://api.github.com',
          headers: {
            'Authorization': 'token $token',
            'Accept': 'application/vnd.github.v3+json',
          },
        ));

  Future<GitHubResult> publish(Website website, {bool isPrivate = false}) async {
    await _createRepo(website.name, isPrivate);
    final base = await _headSha(website.name);
    final tree = await _createBlobs(website.name, _files(website));
    final treeRes = await _dio.post('/repos/$_username/${website.name}/git/trees',
        data: {'base_tree': base, 'tree': tree});
    final commitRes = await _dio.post('/repos/$_username/${website.name}/git/commits', data: {
      'message': 'Portfolio generated by Resumate',
      'tree': treeRes.data['sha'],
      'parents': [base],
    });
    final sha = commitRes.data['sha'] as String;
    await _dio.patch('/repos/$_username/${website.name}/git/refs/heads/main',
        data: {'sha': sha});
    await _enablePages(website.name);
    return GitHubResult(
      repoUrl: 'https://github.com/$_username/${website.name}',
      pagesUrl: 'https://$_username.github.io/${website.name}',
      commitSha: sha,
    );
  }

  Future<void> _createRepo(String name, bool isPrivate) async {
    try {
      await _dio.post('/user/repos', data: {
        'name': name,
        'private': isPrivate,
        'auto_init': true,
        'license_template': 'mit',
      });
    } on DioException catch (e) {
      if (e.response?.statusCode != 422) rethrow;
    }
  }

  Future<String> _headSha(String repo) async {
    final res = await _dio.get('/repos/$_username/$repo/git/ref/heads/main');
    return res.data['object']['sha'] as String;
  }

  Future<List<Map<String, dynamic>>> _createBlobs(
      String repo, Map<String, String> files) async {
    final items = <Map<String, dynamic>>[];
    for (final e in files.entries) {
      final blob = await _dio.post('/repos/$_username/$repo/git/blobs',
          data: {'content': base64Encode(utf8.encode(e.value)), 'encoding': 'base64'});
      items.add({'path': e.key, 'mode': '100644', 'type': 'blob', 'sha': blob.data['sha']});
    }
    return items;
  }

  Future<void> _enablePages(String repo) async {
    try {
      await _dio.post('/repos/$_username/$repo/pages',
          data: {'source': {'branch': 'main', 'path': '/'}});
    } catch (_) {}
  }

  Map<String, String> _files(Website w) => {
        'index.html': w.htmlContent,
        if (w.cssContent != null) 'styles.css': w.cssContent!,
        if (w.jsContent != null) 'script.js': w.jsContent!,
      };
}
